id: P010409
initial_creation_type: ocr
created_at: 23/03/2020
last_modified_at: 2021-12-19 20:48:15.646075
source_metadata:
  id: bdr:W20082
  title: གླིང་སྒྲུང་གི་གཏམ་དཔེ་གཅེས་བསྡུས།
  author: ''
  volumes:
    07faa24ca2dc496d891ec489ab907d43:
      image_group_id: I1KG18126
      title: ''
      volume_number: 1
      total_pages: 508
      base_file: v001.txt
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: true
