id: P010409
initial_creation_type: ocr
source_metadata:
  id: bdr:W20082
  title: གླིང་སྒྲུང་གི་གཏམ་དཔེ་གཅེས་བསྡུས།
  author: ''
  volumes:
    07faa24ca2dc496d891ec489ab907d43:
      image_group_id: I1KG18126
      title: ''
      volume_number: 1
      total_pages: 508
